server:
  port: 8080

bot:
  priority:
    pointsForEnemyPiece0: 0
    pointsForEnemyPiece1: 10
    pointsForEnemyPiece2: 40
    pointsForFriendlyPiece0: 2
    pointsForFriendlyPiece1: 15
    pointsForFriendlyPiece2: 35




